name: lambda

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: "Build, Test and Package"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Prune dependencies for production
        run: npm prune --production

      - name: Run build
        run: npm build

      - name: zip
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r lambda-${{ github.run_number }}.zip dist node_modules package.json
